import { Time } from '@angular/common';

export class Registro {
    constructor(
        public codigo: number,
        public nombre: string,
        public activo: boolean,
        public id?: number,
        public dane?: number,
        public danecod?: number,
        public danenom?: number,
        public servicio?: number, 
        public radicado?: boolean,
        public autoreci?: boolean,
        public fecha?: any,
        public tramite?: number,
        public tramitecod?: string,
        public tramitenom?: string,
        public causal?: number,
        public causalcod?: number,
        public causalnom?: number,
        public causaldetalle?: string,
        public numcuenta?: number, 
        public numcuentaced?: number,
        public numcuentanom?: string,
        public numfactura?: string,
        public respuesta?: number, 
        public respfecha?: any,
        public respradicado?: string,
        public autoresp?: boolean,
        public notifecha?: any,
        public notificacion?: number,
        public notificacioncod?: number,
        public notificacionnom?: number,
        public estado?: string,
    ) {}
}
